### ISSUE TITLE
Before Request Function

### ISSUE THREAD

**Issue by benschaedlich** [HealYouDown/flask-statistics#7]
Hi first of all I want to thank you for your work on this simple but yet efficient extension. I added the extension to my project and I have an issue with passing in a check_if_user_is_allowed() function. 

This function is not being called before each request but only one when initialized. Am I doing something wrong? 

Also if I implement my logic to check the roles in my JWT token I either get: Out of request or application context error - adding a with app.app_context() doesn't help.

`def check_user():`
     `    print("I am Here")`

`stats = Statistics(app, db, Request, before_f=check_user())`

Output:

`
INFO:app.lib.logger:Initalizing Blueprints: Done...
I am Here
[2020-11-12 16:15:44,364] Initalized Flask-Statistics...
DEBUG:app.lib.logger:Initalized Flask-Statistics...
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 296-468-812
[2020-11-12 16:15:52,480] Creating default content...
DEBUG:app.lib.logger:Creating default content...
INFO:werkzeug:127.0.0.1 - - [12/Nov/2020 16:15:52] "GET /statistics/ HTTP/1.1" 200 -
`

**Comment by HealYouDown** [comment]
Hey, it appears that you pass the returned value of your function to `before_f` instead of the function. You have to remove the parentheses: `stats = Statistics(app, db, Request, before_f=check_user)`.

I hope this works, I have not touched that extension for a long time because of missing time.

Thanks for your interest in it though!

**Comment by benschaedlich** [comment]
Thanks a lot for you quick response. It was indeed me passing in the returned value... Thanks for your help!
